import type { PriorityOverrides } from './loot-priority.js';

const ItemID = net.runelite.api.ItemID;

const weaponIds: number[] = [
	ItemID.RUSTY_SWORD as number,
	ItemID.BRONZE_LONGSWORD as number,
	ItemID.IRON_DAGGER as number,
	ItemID.STEEL_LONGSWORD as number,
	ItemID.MITHRIL_SWORD as number,
	ItemID.MITHRIL_LONGSWORD as number,
	ItemID.MITHRIL_2H_SWORD as number,
	ItemID.MITHRIL_WARHAMMER as number,
	ItemID.MITHRIL_AXE as number,
	ItemID.MITHRIL_BATTLEAXE as number,
	ItemID.MITHRIL_PICKAXE as number,
	ItemID.MITHRIL_SPEAR as number,
	ItemID.ADAMANT_LONGSWORD as number,
	ItemID.ADAMANT_AXE as number,
	ItemID.RUNE_SWORD as number,
	ItemID.RUNE_LONGSWORD as number,
	ItemID.RUNE_SCIMITAR as number,
	ItemID.RUNE_MACE as number,
	ItemID.RUNE_DAGGER as number,
	ItemID.RUNE_CLAWS as number,
	ItemID.RUNE_WARHAMMER as number,
	ItemID.RUNE_2H_SWORD as number,
	ItemID.RUNE_BATTLEAXE as number,
	ItemID.RUNE_HALBERD as number,
	ItemID.RUNE_SPEAR as number,
	ItemID.RUNE_AXE as number,
	ItemID.RUNE_PICKAXE as number,
	ItemID.RUNE_CROSSBOW as number,
	ItemID.DRAGON_DAGGER as number,
	ItemID.DRAGON_DAGGERP as number,
	ItemID.DRAGON_LONGSWORD as number,
	ItemID.DRAGON_SCIMITAR as number,
	ItemID.DRAGON_MACE as number,
	ItemID.DRAGON_BATTLEAXE as number,
	ItemID.DRAGON_2H_SWORD as number,
	ItemID.DRAGON_HALBERD as number,
	ItemID.DRAGON_SPEAR as number,
	ItemID.BATTLESTAFF as number,
	ItemID.AIR_BATTLESTAFF as number,
	ItemID.WATER_BATTLESTAFF as number,
	ItemID.EARTH_BATTLESTAFF as number,
	ItemID.FIRE_BATTLESTAFF as number,
	ItemID.MUD_BATTLESTAFF as number,
	ItemID.LAVA_BATTLESTAFF as number,
	ItemID.MAGIC_STAFF as number,
	ItemID.ANCIENT_STAFF as number,
	ItemID.MYSTIC_AIR_STAFF as number,
	ItemID.MYSTIC_WATER_STAFF as number,
	ItemID.MYSTIC_EARTH_STAFF as number,
	ItemID.MYSTIC_FIRE_STAFF as number,
	ItemID.MYSTIC_LAVA_STAFF as number,
];

const armourIds: number[] = [
	ItemID.IRON_FULL_HELM as number,
	ItemID.STEEL_PLATEBODY as number,
	ItemID.STEEL_MED_HELM as number,
	ItemID.STEEL_KITESHIELD as number,
	ItemID.MITHRIL_PLATEBODY as number,
	ItemID.ADAMANT_PLATEBODY as number,
	ItemID.ADAMANT_KITESHIELD as number,
	ItemID.ADAMANT_BOOTS as number,
	ItemID.RUNE_MED_HELM as number,
	ItemID.RUNE_FULL_HELM as number,
	ItemID.RUNE_CHAINBODY as number,
	ItemID.RUNE_PLATEBODY as number,
	ItemID.RUNE_PLATELEGS as number,
	ItemID.RUNE_PLATESKIRT as number,
	ItemID.RUNE_SQ_SHIELD as number,
	ItemID.RUNE_KITESHIELD as number,
	ItemID.DRAGON_MED_HELM as number,
	ItemID.DRAGON_PLATESKIRT as number,
	ItemID.SHIELD_LEFT_HALF as number,
	ItemID.BLACK_SQ_SHIELD as number,
	ItemID.IRON_KITESHIELD as number,
	ItemID.BLACK_DHIDE_BODY as number,
	ItemID.RED_DHIDE_BODY as number,
	ItemID.RED_DHIDE_VAMBRACES as number,
	ItemID.MYSTIC_ROBE_TOP as number,
	ItemID.MYSTIC_ROBE_BOTTOM as number,
	ItemID.MYSTIC_ROBE_TOP_LIGHT as number,
	ItemID.MYSTIC_ROBE_BOTTOM_LIGHT as number,
	ItemID.SPLITBARK_BODY as number,
	ItemID.SPLITBARK_LEGS as number,
	ItemID.ZAMORAK_MONK_TOP as number,
	ItemID.ZAMORAK_MONK_BOTTOM as number,
	ItemID.SPIRIT_SHIELD as number,
	ItemID.AMULET_OF_STRENGTH as number,
	ItemID.AMULET_OF_POWER as number,
	ItemID.BRACELET_OF_ETHEREUM_UNCHARGED as number,
	ItemID.DRAGONSTONE_RING as number,
	ItemID.RING_OF_LIFE as number,
	ItemID.PIRATE_BOOTS as number,
];

export const armourWeapons = {
	weapons: weaponIds,
	armour: armourIds,
	all: [...weaponIds, ...armourIds],
};

export type ArmourWeaponsCategory = 'weapons' | 'armour';

export const armourWeaponsPriorityOverrides: Record<
	ArmourWeaponsCategory,
	PriorityOverrides
> = {
	weapons: {
		[ItemID.RUSTY_SWORD]: 10,
		[ItemID.BRONZE_LONGSWORD]: 10,
		[ItemID.IRON_DAGGER]: 10,
		[ItemID.STEEL_LONGSWORD]: 9,
		[ItemID.MITHRIL_SWORD]: 8,
		[ItemID.MITHRIL_LONGSWORD]: 8,
		[ItemID.MITHRIL_2H_SWORD]: 8,
		[ItemID.MITHRIL_WARHAMMER]: 8,
		[ItemID.MITHRIL_AXE]: 8,
		[ItemID.MITHRIL_BATTLEAXE]: 8,
		[ItemID.MITHRIL_PICKAXE]: 8,
		[ItemID.MITHRIL_SPEAR]: 8,
		[ItemID.ADAMANT_LONGSWORD]: 7,
		[ItemID.ADAMANT_AXE]: 7,
		[ItemID.RUNE_SWORD]: 5,
		[ItemID.RUNE_LONGSWORD]: 5,
		[ItemID.RUNE_SCIMITAR]: 5,
		[ItemID.RUNE_MACE]: 5,
		[ItemID.RUNE_DAGGER]: 5,
		[ItemID.RUNE_CLAWS]: 5,
		[ItemID.RUNE_WARHAMMER]: 5,
		[ItemID.RUNE_2H_SWORD]: 5,
		[ItemID.RUNE_BATTLEAXE]: 5,
		[ItemID.RUNE_HALBERD]: 4,
		[ItemID.RUNE_SPEAR]: 5,
		[ItemID.RUNE_AXE]: 5,
		[ItemID.RUNE_PICKAXE]: 5,
		[ItemID.RUNE_CROSSBOW]: 4,
		[ItemID.DRAGON_DAGGER]: 3,
		[ItemID.DRAGON_DAGGERP]: 3,
		[ItemID.DRAGON_LONGSWORD]: 3,
		[ItemID.DRAGON_SCIMITAR]: 3,
		[ItemID.DRAGON_MACE]: 3,
		[ItemID.DRAGON_BATTLEAXE]: 2,
		[ItemID.DRAGON_2H_SWORD]: 1,
		[ItemID.DRAGON_HALBERD]: 1,
		[ItemID.DRAGON_SPEAR]: 1,
		[ItemID.BATTLESTAFF]: 7,
		[ItemID.AIR_BATTLESTAFF]: 6,
		[ItemID.WATER_BATTLESTAFF]: 6,
		[ItemID.EARTH_BATTLESTAFF]: 6,
		[ItemID.FIRE_BATTLESTAFF]: 6,
		[ItemID.MUD_BATTLESTAFF]: 3,
		[ItemID.LAVA_BATTLESTAFF]: 3,
		[ItemID.MAGIC_STAFF]: 9,
		[ItemID.ANCIENT_STAFF]: 2,
		[ItemID.MYSTIC_AIR_STAFF]: 3,
		[ItemID.MYSTIC_WATER_STAFF]: 3,
		[ItemID.MYSTIC_EARTH_STAFF]: 3,
		[ItemID.MYSTIC_FIRE_STAFF]: 3,
		[ItemID.MYSTIC_LAVA_STAFF]: 2,
	},

	armour: {
		[ItemID.IRON_FULL_HELM]: 10,
		[ItemID.STEEL_PLATEBODY]: 10,
		[ItemID.STEEL_MED_HELM]: 10,
		[ItemID.STEEL_KITESHIELD]: 10,
		[ItemID.MITHRIL_PLATEBODY]: 9,
		[ItemID.ADAMANT_PLATEBODY]: 8,
		[ItemID.ADAMANT_KITESHIELD]: 8,
		[ItemID.ADAMANT_BOOTS]: 8,
		[ItemID.RUNE_MED_HELM]: 5,
		[ItemID.RUNE_FULL_HELM]: 5,
		[ItemID.RUNE_CHAINBODY]: 5,
		[ItemID.RUNE_PLATEBODY]: 4,
		[ItemID.RUNE_PLATELEGS]: 4,
		[ItemID.RUNE_PLATESKIRT]: 4,
		[ItemID.RUNE_SQ_SHIELD]: 5,
		[ItemID.RUNE_KITESHIELD]: 5,
		[ItemID.DRAGON_MED_HELM]: 3,
		[ItemID.DRAGON_PLATESKIRT]: 2,
		[ItemID.SHIELD_LEFT_HALF]: 1,
		[ItemID.BLACK_SQ_SHIELD]: 10,
		[ItemID.IRON_KITESHIELD]: 10,
		[ItemID.BLACK_DHIDE_BODY]: 5,
		[ItemID.RED_DHIDE_BODY]: 6,
		[ItemID.RED_DHIDE_VAMBRACES]: 7,
		[ItemID.MYSTIC_ROBE_TOP]: 3,
		[ItemID.MYSTIC_ROBE_BOTTOM]: 3,
		[ItemID.MYSTIC_ROBE_TOP_LIGHT]: 3,
		[ItemID.MYSTIC_ROBE_BOTTOM_LIGHT]: 3,
		[ItemID.SPLITBARK_BODY]: 4,
		[ItemID.SPLITBARK_LEGS]: 4,
		[ItemID.ZAMORAK_MONK_TOP]: 8,
		[ItemID.ZAMORAK_MONK_BOTTOM]: 8,
		[ItemID.SPIRIT_SHIELD]: 2,
		[ItemID.AMULET_OF_STRENGTH]: 5,
		[ItemID.AMULET_OF_POWER]: 5,
		[ItemID.BRACELET_OF_ETHEREUM_UNCHARGED]: 2,
		[ItemID.DRAGONSTONE_RING]: 2,
		[ItemID.RING_OF_LIFE]: 7,
		[ItemID.PIRATE_BOOTS]: 10,
	},
};
