import type { PriorityOverrides } from './loot-priority.js';

const ItemID = net.runelite.api.ItemID;

const cookedFoodIds: number[] = [
	ItemID.CHEESE as number,
	ItemID.TROUT as number,
	ItemID.TUNA as number,
	ItemID.LOBSTER as number,
	ItemID.BASS as number,
	ItemID.SWORDFISH as number,
	ItemID.MONKFISH as number,
	ItemID.SHARK as number,
	ItemID.SEA_TURTLE as number,
	ItemID.MANTA_RAY as number,
	ItemID.ANGLERFISH as number,
	ItemID.DARK_CRAB as number,
	ItemID.BLIGHTED_ANGLERFISH as number,
	ItemID.BLIGHTED_KARAMBWAN as number,
	ItemID.BLIGHTED_MANTA_RAY as number,
	ItemID.ANCHOVY_PIZZA as number,
	ItemID.PINEAPPLE_PIZZA as number,
	ItemID.POTATO_WITH_CHEESE as number,
	ItemID.EGG_POTATO as number,
	ItemID.TUNA_POTATO as number,
	ItemID.MUSHROOM_POTATO as number,
	ItemID.CHILLI_POTATO as number,
	ItemID.SUMMER_PIE as number,
	ItemID.WILD_PIE as number,
	ItemID.SPINACH_ROLL as number,
	ItemID.UGTHANKI_KEBAB as number,
	ItemID.WATERMELON as number,
	ItemID.SWEETCORN as number,
];

const rawFoodIds: number[] = [
	ItemID.RAW_SWORDFISH as number,
	ItemID.RAW_MONKFISH as number,
	ItemID.RAW_SHARK as number,
	ItemID.RAW_SEA_TURTLE as number,
	ItemID.RAW_MANTA_RAY as number,
];

const potionIds: number[] = [
	ItemID.PRAYER_POTION2 as number,
	ItemID.PRAYER_POTION3 as number,
	ItemID.PRAYER_POTION4 as number,
	ItemID.RESTORE_POTION2 as number,
	ItemID.SUPER_RESTORE3 as number,
	ItemID.SUPER_RESTORE4 as number,
	ItemID.SUPER_RESTORE_MIX2 as number,
	ItemID.BLIGHTED_SUPER_RESTORE3 as number,
	ItemID.BLIGHTED_SUPER_RESTORE4 as number,
	ItemID.SUPER_ATTACK2 as number,
	ItemID.SUPER_ATTACK3 as number,
	ItemID.SUPER_STRENGTH1 as number,
	ItemID.SUPER_STRENGTH2 as number,
	ItemID.SUPER_STRENGTH3 as number,
	ItemID.SUPER_DEFENCE2 as number,
	ItemID.SUPER_DEFENCE3 as number,
	ItemID.SUPER_COMBAT_POTION1 as number,
	ItemID.SUPER_COMBAT_POTION2 as number,
	ItemID.RANGING_POTION1 as number,
	ItemID.RANGING_POTION2 as number,
	ItemID.RANGING_POTION3 as number,
	ItemID.MAGIC_POTION2 as number,
	ItemID.MAGIC_POTION3 as number,
	ItemID.SUPERANTIPOISON2 as number,
	ItemID.ANTIDOTE3 as number,
	ItemID.ANTIDOTE4 as number,
	ItemID.ANTIFIRE_POTION2 as number,
	ItemID.ZAMORAK_BREW2 as number,
	ItemID.ZAMORAK_BREW3 as number,
	ItemID.ANCIENT_BREW2 as number,
	ItemID.ANCIENT_BREW3 as number,
	ItemID.SARADOMIN_BREW3 as number,
	ItemID.SARADOMIN_BREW4 as number,
	ItemID.SANFEW_SERUM3 as number,
	ItemID.SANFEW_SERUM4 as number,
	ItemID.ZAMORAK_MIX2 as number,
	ItemID.BLIGHTED_ANCIENT_ICE_SACK as number,
	ItemID.BLIGHTED_ENTANGLE_SACK as number,
	ItemID.BLIGHTED_TELEPORT_SPELL_SACK as number,
	ItemID.BLIGHTED_VENGEANCE_SACK as number,
];

export const combatSupplies = {
	cookedFood: cookedFoodIds,
	rawFood: rawFoodIds,
	potions: potionIds,
	all: [...cookedFoodIds, ...rawFoodIds, ...potionIds],
};

export type CombatSuppliesCategory = 'cookedFood' | 'rawFood' | 'potions';

export const combatSuppliesPriorityOverrides: Record<
	CombatSuppliesCategory,
	PriorityOverrides
> = {
	cookedFood: {
		[ItemID.CHEESE as number]: 10,
		[ItemID.TROUT as number]: 9,
		[ItemID.TUNA as number]: 8,
		[ItemID.LOBSTER as number]: 7,
		[ItemID.BASS as number]: 6,
		[ItemID.SWORDFISH as number]: 5,
		[ItemID.MONKFISH as number]: 4,
		[ItemID.SHARK as number]: 3,
		[ItemID.SEA_TURTLE as number]: 1,
		[ItemID.MANTA_RAY as number]: 1,
		[ItemID.ANGLERFISH as number]: 2,
		[ItemID.DARK_CRAB as number]: 2,
		[ItemID.BLIGHTED_ANGLERFISH as number]: 2,
		[ItemID.BLIGHTED_KARAMBWAN as number]: 3,
		[ItemID.BLIGHTED_MANTA_RAY as number]: 1,
		[ItemID.ANCHOVY_PIZZA as number]: 9,
		[ItemID.PINEAPPLE_PIZZA as number]: 9,
		[ItemID.POTATO_WITH_CHEESE as number]: 7,
		[ItemID.EGG_POTATO as number]: 9,
		[ItemID.TUNA_POTATO as number]: 8,
		[ItemID.MUSHROOM_POTATO as number]: 9,
		[ItemID.CHILLI_POTATO as number]: 8,
		[ItemID.SUMMER_PIE as number]: 9,
		[ItemID.WILD_PIE as number]: 9,
		[ItemID.SPINACH_ROLL as number]: 10,
		[ItemID.UGTHANKI_KEBAB as number]: 10,
		[ItemID.WATERMELON as number]: 10,
		[ItemID.SWEETCORN as number]: 10,
	},
	rawFood: {
		[ItemID.RAW_SWORDFISH as number]: 5,
		[ItemID.RAW_MONKFISH as number]: 4,
		[ItemID.RAW_SHARK as number]: 3,
		[ItemID.RAW_SEA_TURTLE as number]: 1,
		[ItemID.RAW_MANTA_RAY as number]: 1,
	},
	potions: {
		[ItemID.PRAYER_POTION2 as number]: 5,
		[ItemID.PRAYER_POTION3 as number]: 4,
		[ItemID.PRAYER_POTION4 as number]: 3,
		[ItemID.RESTORE_POTION2 as number]: 9,
		[ItemID.SUPER_RESTORE3 as number]: 3,
		[ItemID.SUPER_RESTORE4 as number]: 2,
		[ItemID.SUPER_RESTORE_MIX2 as number]: 6,
		[ItemID.BLIGHTED_SUPER_RESTORE3 as number]: 5,
		[ItemID.BLIGHTED_SUPER_RESTORE4 as number]: 4,
		[ItemID.SUPER_ATTACK2 as number]: 9,
		[ItemID.SUPER_ATTACK3 as number]: 8,
		[ItemID.SUPER_STRENGTH1 as number]: 10,
		[ItemID.SUPER_STRENGTH2 as number]: 9,
		[ItemID.SUPER_STRENGTH3 as number]: 8,
		[ItemID.SUPER_DEFENCE2 as number]: 9,
		[ItemID.SUPER_DEFENCE3 as number]: 8,
		[ItemID.SUPER_COMBAT_POTION1 as number]: 5,
		[ItemID.SUPER_COMBAT_POTION2 as number]: 4,
		[ItemID.RANGING_POTION1 as number]: 8,
		[ItemID.RANGING_POTION2 as number]: 7,
		[ItemID.RANGING_POTION3 as number]: 6,
		[ItemID.MAGIC_POTION2 as number]: 9,
		[ItemID.MAGIC_POTION3 as number]: 8,
		[ItemID.SUPERANTIPOISON2 as number]: 6,
		[ItemID.ANTIDOTE3 as number]: 5,
		[ItemID.ANTIDOTE4 as number]: 4,
		[ItemID.ANTIFIRE_POTION2 as number]: 6,
		[ItemID.ZAMORAK_BREW2 as number]: 9,
		[ItemID.ZAMORAK_BREW3 as number]: 8,
		[ItemID.ANCIENT_BREW2 as number]: 8,
		[ItemID.ANCIENT_BREW3 as number]: 7,
		[ItemID.SARADOMIN_BREW3 as number]: 3,
		[ItemID.SARADOMIN_BREW4 as number]: 3,
		[ItemID.SANFEW_SERUM3 as number]: 2,
		[ItemID.SANFEW_SERUM4 as number]: 1,
		[ItemID.ZAMORAK_MIX2 as number]: 9,
		[ItemID.BLIGHTED_ANCIENT_ICE_SACK as number]: 4,
		[ItemID.BLIGHTED_ENTANGLE_SACK as number]: 4,
		[ItemID.BLIGHTED_TELEPORT_SPELL_SACK as number]: 4,
		[ItemID.BLIGHTED_VENGEANCE_SACK as number]: 4,
	},
};
