import type { PriorityOverrides } from './loot-priority.js';

const ItemID = net.runelite.api.ItemID;

const resourceIds: number[] = [
	ItemID.COINS_995 as number,
	ItemID.PURE_ESSENCE as number,
	ItemID.AETHER_CATALYST as number,
	ItemID.GRAPES as number,
	ItemID.BUCKET_OF_SAND as number,
	ItemID.MAPLE_LOGS as number,
	ItemID.YEW_LOGS as number,
	ItemID.MAGIC_LOGS as number,
	ItemID.MAHOGANY_LOGS as number,
	ItemID.OAK_PLANK as number,
	ItemID.TEAK_PLANK as number,
	ItemID.MAHOGANY_PLANK as number,
	ItemID.DRAGON_BONES as number,
	ItemID.SHARK_LURE as number,
	ItemID.OYSTER_PEARLS as number,
	ItemID.LOOP_HALF_OF_KEY as number,
	ItemID.TOOTH_HALF_OF_KEY as number,
	ItemID.AIR_TALISMAN as number,
	ItemID.MIND_TALISMAN as number,
	ItemID.EARTH_TALISMAN as number,
	ItemID.FIRE_TALISMAN as number,
	ItemID.BODY_TALISMAN as number,
	ItemID.CHAOS_TALISMAN as number,
	ItemID.COSMIC_TALISMAN as number,
	ItemID.NATURE_TALISMAN as number,
	ItemID.LAW_TALISMAN as number,
	ItemID.DEATH_TALISMAN as number,
	ItemID.WRATH_TALISMAN as number,
	ItemID.UNPOWERED_ORB as number,
	ItemID.AIR_ORB as number,
	ItemID.WATER_ORB as number,
	ItemID.EARTH_ORB as number,
	ItemID.FIRE_ORB as number,
];

const materialIds: number[] = [
	ItemID.WHITE_BERRIES as number,
	ItemID.LIMPWURT_ROOT as number,
	ItemID.WINE_OF_ZAMORAK as number,
	ItemID.POTATO_CACTUS as number,
	ItemID.CACTUS_SPINE as number,
	ItemID.DESERT_GOAT_HORN as number,
	ItemID.FEATHER as number,
	ItemID.BEER as number,
	ItemID.BASKET as number,
	ItemID.GRYPHON_FEATHER as number,
	ItemID.TINDERBOX as number,
	ItemID.JUG_OF_WATER as number,
	ItemID.SUPERCOMPOST as number,
	ItemID.DARK_FISHING_BAIT as number,
	ItemID.COCONUT as number,
	ItemID.SEAWEED as number,
	ItemID.EDIBLE_SEAWEED as number,
	ItemID.HARPOON as number,
	ItemID.BUCKET as number,
	ItemID.RED_SPIDERS_EGGS as number,
	ItemID.UNICORN_HORN as number,
	ItemID.MORT_MYRE_FUNGUS as number,
	ItemID.BARK as number,
	ItemID.MOLTEN_GLASS as number,
	ItemID.SNAKESKIN as number,
	ItemID.SWAMP_TAR as number,
	ItemID.SPIDER_CARCASS as number,
	ItemID.HOLY_ELIXIR as number,
	ItemID.BLOOD_ESSENCE as number,
	ItemID.RUNITE_LIMBS as number,
	ItemID.WEAPON_POISON_5940 as number, // weapon poison ++
	ItemID.BINDING_NECKLACE as number,
	ItemID.UNHOLY_SYMBOL as number,
	ItemID.CRYSTAL_KEY as number,
	ItemID.LONG_BONE as number,
	ItemID.ASHES as number,
	ItemID.BLESSED_BONE_SHARDS as number,
	ItemID.SUNKISSED_BONES as number,
	ItemID.SUNFIRE_SPLINTERS as number,
	ItemID.ARAXYTE_VENOM_SACK as number,
	ItemID.DIABOLIC_WORMS as number,
	ItemID.BARREL_OF_DEMONIC_TALLOW_FULL as number,
	ItemID.ZULANDRA_TELEPORT as number,
	ItemID.ZULRAHS_SCALES as number,
	ItemID.DEMON_TEAR as number,
	ItemID.MOKHAIOTL_WAYSTONE as number,
	ItemID.CHASM_TELEPORT_SCROLL as number,
	ItemID.DESICCATED_PAGE as number,
	ItemID.WILDERNESS_CRABS_TELEPORT as number,
	ItemID.REVENANT_CAVE_TELEPORT as number,
	ItemID.SOILED_PAGE as number,
	ItemID.ECUMENICAL_KEY_SHARD as number,
	ItemID.NIHIL_SHARD as number,
	ItemID.KEY_MASTER_TELEPORT as number,
	ItemID.SINISTER_KEY as number,
	ItemID.MUDDY_KEY as number,
	ItemID.SPIDER_CAVE_TELEPORT as number,
];

const dragonhideIds: number[] = [
	ItemID.GREEN_DRAGONHIDE as number,
	ItemID.BLUE_DRAGONHIDE as number,
	ItemID.RED_DRAGONHIDE as number,
	ItemID.BLACK_DRAGONHIDE as number,
	ItemID.SCALY_BLUE_DRAGONHIDE as number,
];

export const generalLoot = {
	resources: resourceIds,
	dragonhide: dragonhideIds,
	materials: materialIds,
	all: [...resourceIds, ...dragonhideIds, ...materialIds],
};

export type GeneralLootCategory = 'resources' | 'dragonhide' | 'materials';

export const generalLootPriorityOverrides: Record<
	GeneralLootCategory,
	PriorityOverrides
> = {
	resources: {
		[ItemID.COINS_995]: 2,
		[ItemID.PURE_ESSENCE]: 9,
		[ItemID.AETHER_CATALYST]: 3,
		[ItemID.GRAPES]: 10,
		[ItemID.BUCKET_OF_SAND]: 9,
		[ItemID.MAPLE_LOGS]: 6,
		[ItemID.YEW_LOGS]: 5,
		[ItemID.MAGIC_LOGS]: 4,
		[ItemID.MAHOGANY_LOGS]: 7,
		[ItemID.OAK_PLANK]: 9,
		[ItemID.TEAK_PLANK]: 8,
		[ItemID.MAHOGANY_PLANK]: 7,
		[ItemID.DRAGON_BONES]: 2,
		[ItemID.SHARK_LURE]: 7,
		[ItemID.OYSTER_PEARLS]: 10,
		[ItemID.LOOP_HALF_OF_KEY]: 1,
		[ItemID.TOOTH_HALF_OF_KEY]: 1,
		[ItemID.AIR_TALISMAN]: 10,
		[ItemID.MIND_TALISMAN]: 10,
		[ItemID.EARTH_TALISMAN]: 10,
		[ItemID.FIRE_TALISMAN]: 10,
		[ItemID.BODY_TALISMAN]: 10,
		[ItemID.CHAOS_TALISMAN]: 8,
		[ItemID.COSMIC_TALISMAN]: 7,
		[ItemID.NATURE_TALISMAN]: 6,
		[ItemID.LAW_TALISMAN]: 5,
		[ItemID.DEATH_TALISMAN]: 4,
		[ItemID.WRATH_TALISMAN]: 3,
		[ItemID.UNPOWERED_ORB]: 7,
		[ItemID.AIR_ORB]: 6,
		[ItemID.WATER_ORB]: 5,
		[ItemID.EARTH_ORB]: 4,
		[ItemID.FIRE_ORB]: 3,
	},
	dragonhide: {
		[ItemID.GREEN_DRAGONHIDE]: 10,
		[ItemID.BLUE_DRAGONHIDE]: 9,
		[ItemID.RED_DRAGONHIDE]: 8,
		[ItemID.BLACK_DRAGONHIDE]: 7,
		[ItemID.SCALY_BLUE_DRAGONHIDE]: 8,
	},
	materials: {
		[ItemID.WHITE_BERRIES]: 5,
		[ItemID.LIMPWURT_ROOT]: 6,
		[ItemID.WINE_OF_ZAMORAK]: 3,
		[ItemID.POTATO_CACTUS]: 4,
		[ItemID.CACTUS_SPINE]: 6,
		[ItemID.DESERT_GOAT_HORN]: 5,
		[ItemID.FEATHER]: 10,
		[ItemID.BEER]: 10,
		[ItemID.BASKET]: 10,
		[ItemID.GRYPHON_FEATHER]: 8,
		[ItemID.TINDERBOX]: 10,
		[ItemID.JUG_OF_WATER]: 10,
		[ItemID.SUPERCOMPOST]: 10,
		[ItemID.DARK_FISHING_BAIT]: 7,
		[ItemID.COCONUT]: 6,
		[ItemID.SEAWEED]: 10,
		[ItemID.EDIBLE_SEAWEED]: 7,
		[ItemID.HARPOON]: 10,
		[ItemID.BUCKET]: 10,
		[ItemID.RED_SPIDERS_EGGS]: 3,
		[ItemID.UNICORN_HORN]: 5,
		[ItemID.MORT_MYRE_FUNGUS]: 9,
		[ItemID.BARK]: 10,
		[ItemID.MOLTEN_GLASS]: 10,
		[ItemID.SNAKESKIN]: 10,
		[ItemID.SWAMP_TAR]: 10,
		[ItemID.SPIDER_CARCASS]: 10,
		[ItemID.HOLY_ELIXIR]: 2,
		[ItemID.BLOOD_ESSENCE]: 1,
		[ItemID.RUNITE_LIMBS]: 3,
		[ItemID.WEAPON_POISON_5940]: 10, // weapon poison ++
		[ItemID.BINDING_NECKLACE]: 10,
		[ItemID.UNHOLY_SYMBOL]: 10,
		[ItemID.CRYSTAL_KEY]: 1,
		[ItemID.LONG_BONE]: 1,
		[ItemID.ASHES]: 10,
		[ItemID.BLESSED_BONE_SHARDS]: 4,
		[ItemID.SUNKISSED_BONES]: 3,
		[ItemID.SUNFIRE_SPLINTERS]: 2,
		[ItemID.ARAXYTE_VENOM_SACK]: 3,
		[ItemID.DIABOLIC_WORMS]: 3,
		[ItemID.BARREL_OF_DEMONIC_TALLOW_FULL]: 10,
		[ItemID.ZULANDRA_TELEPORT]: 1,
		[ItemID.ZULRAHS_SCALES]: 2,
		[ItemID.DEMON_TEAR]: 2,
		[ItemID.MOKHAIOTL_WAYSTONE]: 2,
		[ItemID.CHASM_TELEPORT_SCROLL]: 3,
		[ItemID.DESICCATED_PAGE]: 4,
		[ItemID.WILDERNESS_CRABS_TELEPORT]: 3,
		[ItemID.REVENANT_CAVE_TELEPORT]: 3,
		[ItemID.SOILED_PAGE]: 4,
		[ItemID.ECUMENICAL_KEY_SHARD]: 2,
		[ItemID.NIHIL_SHARD]: 1,
		[ItemID.KEY_MASTER_TELEPORT]: 3,
		[ItemID.SINISTER_KEY]: 6,
		[ItemID.MUDDY_KEY]: 6,
		[ItemID.SPIDER_CAVE_TELEPORT]: 3,
	},
};
